name: Annotation Agreement Calculation

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  run-agreement:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install pandas scikit-learn
          fi

      - name: Run Python Code
        run: python "python_code.py"

      - name: Upload results artifact
        uses: actions/upload-artifact@v4
        with:
          name: AnnotationResults
          path: Final_Result.xlsx
