name: Annotation Agreement Calculation

on:
  push:
    branches: [ main ]         # Run on pushes to the main branch (adjust as needed)
  workflow_dispatch:           # Allow manual triggering of the workflow

jobs:
  run-agreement:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install pandas scikit-learn
          fi

      - name: python code 
        run: python python code.py

      - name: Upload results artifact
        uses: actions/upload-artifact@v3
        with:
          name: AnnotationResults   # Artifact name
          path: Final_Result.xlsx   # Path to the output Excel file
